[project]
name = "pose-eval"
version = "0.1.0"
description = "Pose evaluation with beacon data replay"
readme = "README.md"
authors = [
    { name = "John Holman", email = "john.g.holman@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "pyarrow",
    "PySide6 ; sys_platform == 'win32'",
    "matplotlib ; sys_platform == 'win32'",
    "scipy-stubs~=1.18.0",
    "pandas-stubs~=3.0.3",
]

[project.scripts]
pose-eval = "pose_eval.main:cli"

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.15.20",
]
